### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by biswapriyamisra** [Philipbear/BUDDY_Metabolomics#4]
![image](https://user-images.githubusercontent.com/27797664/212084883-7a84efa4-3b2e-4281-8606-a052decf4b59.png)

Hi Philip,

After Tao's talk yesterday at WCMC, UC Davis, wanted to try out BUDDY!
Installation issue. using Windows 11, and all updated.
The attached certificate in the bundled also installed.
Wonder how to cross this 1st hurdle!

Thanks again,
Biswa

**Comment by Philipbear** [comment]
Hi Biswa,

Thanks so much for reporting this issue. I have updated the app certificate in the latest release (BUDDY ver1.6). Please feel free to give a try. Make sure to install the app by right clicking "install.ps1" and "Run with Powershell". You might need to install the certificate during this process. I tested it on my Win10 PC and it worked fine. I hope this could solve your issue. Thanks again.

Best,
Shipei
