### ISSUE TITLE
Windows cannot install package

### ISSUE THREAD

**Issue by Angrist75** [Philipbear/BUDDY_Metabolomics#5]
I want to use the software but from what you can see in the attachment there is a software incompatibility. Is it possible to overcome this? 
all the Best
Andrea
[Buddy_Error.pptx](https://github.com/Philipbear/BUDDY_Metabolomics/files/11233681/Buddy_Error.pptx)

**Comment by Philipbear** [comment]
Hi Andrea,

It looks like that it is related to the version of the operating system.

You may first try to change the execution policy by selecting "Yes to All", and then continue the installation process. If that doesn't work, please consider update the windows version (https://support.microsoft.com/en-us/windows/get-the-latest-windows-update-7d20e88c-0568-483a-37bc-c3885390d212).

Hope this helps you.

Best,
Shipei
