### ISSUE TITLE
mzML conversion settings

### ISSUE THREAD

**Issue by karlssoc** [Philipbear/BUDDY_Metabolomics#7]
I was trying to run BUDDY on some orbitrap metabolomics files, but the mzML files could not be loaded.

I only got this error message in a pop up window
```
Error invalid file format
```
I tried centrioded mzMLs from both proteowizard or thermorawfileparser with and without index, but all failed.

I would be grateful for the need conversion settings.

Thanks

**Comment by Philipbear** [comment]
Hi,

1. We only accept DDA-based mzML files.
2. Should you have any question with file conversion, please refer to [here](https://ccms-ucsd.github.io/GNPSDocumentation/fileconversion/). Some settings are necessary for valid file conversion./

Hope this addresses your issue. Thanks.
