### ISSUE TITLE
Since the second time search, the exe is keep crashing

### ISSUE THREAD

**Issue by vhaozhang** [Philipbear/BUDDY_Metabolomics#8]
Dear Sir/Madam,

I knew your project via nature journal , I downloaded it and try it. The first time ran smoothly,but it keeps crashing since the second time. The the software noticed: MS2 Library searching... The process would be shutted down.

Could you give some advices on how to fix that?

**Comment by vhaozhang** [comment]
Even i use the demo data, it still broken down when "MS2 Library searching... "

**Comment by Philipbear** [comment]
Hi there,

If the bug is repeatable, it would be great if you can tell us what demo data you are using and the BUDDY settings (any setting other than default). Thanks.

**Comment by vhaozhang** [comment]
I made a Restore Setting then I just click  MS2 library in basic setting .
The demo data was [project-new single research]-demo data as follows:
MS1: 
283.1864	359645
284.1895	46830
285.1914	7021
 MS2 
68.0492	491
70.0648	20896
74.0597	230
80.0492	234
81.0571	420
82.065	115
86.0598	4990
94.0649	5423
98.0599	556
100.0757	213
104.0704	1022
108.0806	199
114.0912	784
116.0705	1055
126.0911	794
134.081	1841
144.1017	2071
162.1122	2106

In fact ,i made an error video on Youtube,  [https://youtu.be/-nP4sih25Ks], it's private video. And i will delete it after the issue fixed. Please have a check

**Comment by Philipbear** [comment]
Hi, thanks for the video. It looks like you might need more RAM to run BUDDY to avoid crashing, as these bugs can not be repeated on my PC.

**Comment by vhaozhang** [comment]
THX for your reply . And i will try in another PC
